name: fleetpy_linux
channels:
  - conda-forge
dependencies:
  - python=3.9
  - pip

  # core scientific stack
  - numpy
  - pandas
  - scipy
  - scikit-learn
  - networkx

  # geometry / routing deps
  - shapely
  - pyproj
  - libspatialindex
  - rtree
  - osmnx

  # utilities / plotting
  - tqdm
  - matplotlib
  - geographiclib
  - geopy
  - click

  # If your repo needs extra pip-only packages, add them here later
  # - pip:
  #     - ax-platform
  #     - botorch
  #     - gpytorch
